#!/usr/bin/env python3
"""Generate typings for icon/chart libraries by scanning what the app imports.

Why this exists
---------------
`tsc` needs type declarations for every imported package. In an environment
with no npm registry access we cannot install `lucide-react` or `recharts`, so
this script reads the app's own import statements and emits a `.d.ts` that
declares exactly the symbols the app actually uses.

That makes the offline type-check *stricter* than a hand-written stub: if
someone imports an icon that does not exist, the generated stub will not
contain it either, so the error surfaces at build time on a real machine.

Run:  python3 tools/typecheck/generate_stubs.py
"""
from __future__ import annotations

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC = ROOT / "frontend" / "src"
STUBS = pathlib.Path(__file__).resolve().parent / "stubs"

#: `import { A, B as C } from 'pkg'` - captures the braced clause.
IMPORT_RE = re.compile(
    r"import\s+(?:type\s+)?\{([^}]+)\}\s+from\s+['\"](?P<pkg>[^'\"]+)['\"]",
    re.S,
)


def imported_symbols(package: str) -> list[str]:
    """Every symbol the app imports from `package`, deduplicated and sorted."""
    found: set[str] = set()
    for path in SRC.rglob("*.ts*"):
        for match in IMPORT_RE.finditer(path.read_text(encoding="utf-8")):
            if match.group("pkg") != package:
                continue
            for raw in match.group(1).split(","):
                name = raw.strip()
                if not name:
                    continue
                # `Foo as Bar` - the stub must declare `Foo`, the exported name.
                name = name.split(" as ")[0].strip()
                if name.startswith("type "):
                    name = name[5:].strip()
                if re.fullmatch(r"[A-Za-z_$][\w$]*", name):
                    found.add(name)
    return sorted(found)


LUCIDE_TEMPLATE = """\
/**
 * GENERATED by tools/typecheck/generate_stubs.py - do not edit by hand.
 *
 * Declares exactly the icons this app imports, so `tsc` can run without the
 * npm registry. Re-run the generator after adding a new icon import.
 */
declare module 'lucide-react' {{
  import type {{ ReactElement, SVGProps }} from 'react'

  export interface LucideProps extends SVGProps<SVGSVGElement> {{
    size?: string | number
    absoluteStrokeWidth?: boolean
  }}
  export type LucideIcon = (props: LucideProps) => ReactElement | null

{icons}
}}
"""

RECHARTS_TEMPLATE = """\
/**
 * GENERATED by tools/typecheck/generate_stubs.py - do not edit by hand.
 *
 * Recharts components accept a large, loosely-typed prop surface. For offline
 * checking we only need the import to resolve and children to be accepted, so
 * every component is declared as taking an open prop bag. The real typings are
 * used on a machine that can run `npm install`.
 */
declare module 'recharts' {{
  import type {{ ReactElement, ReactNode }} from 'react'

  export interface RechartsProps {{
    children?: ReactNode
    [prop: string]: unknown
  }}
  export type RechartsComponent = (props: RechartsProps) => ReactElement | null

{components}
}}
"""


def main() -> int:
    lucide = imported_symbols("lucide-react")
    recharts = imported_symbols("recharts")

    if not lucide:
        print("warning: no lucide-react imports found", file=sys.stderr)

    (STUBS / "lucide-react").mkdir(parents=True, exist_ok=True)
    (STUBS / "lucide-react" / "index.d.ts").write_text(
        LUCIDE_TEMPLATE.format(
            icons="\n".join(f"  export const {name}: LucideIcon" for name in lucide)
        ),
        encoding="utf-8",
    )

    (STUBS / "recharts").mkdir(parents=True, exist_ok=True)
    (STUBS / "recharts" / "index.d.ts").write_text(
        RECHARTS_TEMPLATE.format(
            components="\n".join(
                f"  export const {name}: RechartsComponent" for name in recharts
            )
        ),
        encoding="utf-8",
    )

    print(f"lucide-react: {len(lucide)} icons declared")
    print(f"recharts:     {len(recharts)} components declared")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
