/**
 * GENERATED by tools/typecheck/generate_stubs.py - do not edit by hand.
 *
 * Recharts components accept a large, loosely-typed prop surface. For offline
 * checking we only need the import to resolve and children to be accepted, so
 * every component is declared as taking an open prop bag. The real typings are
 * used on a machine that can run `npm install`.
 */
declare module 'recharts' {
  import type { ReactElement, ReactNode } from 'react'

  export interface RechartsProps {
    children?: ReactNode
    [prop: string]: unknown
  }
  export type RechartsComponent = (props: RechartsProps) => ReactElement | null

  export const Area: RechartsComponent
  export const AreaChart: RechartsComponent
  export const Bar: RechartsComponent
  export const BarChart: RechartsComponent
  export const CartesianGrid: RechartsComponent
  export const Cell: RechartsComponent
  export const Legend: RechartsComponent
  export const Line: RechartsComponent
  export const LineChart: RechartsComponent
  export const Pie: RechartsComponent
  export const PieChart: RechartsComponent
  export const ResponsiveContainer: RechartsComponent
  export const Tooltip: RechartsComponent
  export const XAxis: RechartsComponent
  export const YAxis: RechartsComponent
}
