/**
 * GENERATED by tools/typecheck/generate_stubs.py - do not edit by hand.
 *
 * Declares exactly the icons this app imports, so `tsc` can run without the
 * npm registry. Re-run the generator after adding a new icon import.
 */
declare module 'lucide-react' {
  import type { ReactElement, SVGProps } from 'react'

  export interface LucideProps extends SVGProps<SVGSVGElement> {
    size?: string | number
    absoluteStrokeWidth?: boolean
  }
  export type LucideIcon = (props: LucideProps) => ReactElement | null

  export const Activity: LucideIcon
  export const AlertTriangle: LucideIcon
  export const ArrowLeft: LucideIcon
  export const ArrowRight: LucideIcon
  export const ArrowRightLeft: LucideIcon
  export const Banknote: LucideIcon
  export const BarChart3: LucideIcon
  export const BrainCircuit: LucideIcon
  export const Building2: LucideIcon
  export const CalendarClock: LucideIcon
  export const CalendarDays: LucideIcon
  export const Check: LucideIcon
  export const CheckCircle2: LucideIcon
  export const ChevronDown: LucideIcon
  export const ChevronLeft: LucideIcon
  export const ChevronRight: LucideIcon
  export const ClipboardCheck: LucideIcon
  export const ClipboardList: LucideIcon
  export const Clock: LucideIcon
  export const Compass: LucideIcon
  export const Contrast: LucideIcon
  export const Cpu: LucideIcon
  export const Download: LucideIcon
  export const ExternalLink: LucideIcon
  export const FileDown: LucideIcon
  export const FileSearch: LucideIcon
  export const FileSpreadsheet: LucideIcon
  export const FileText: LucideIcon
  export const FileUp: LucideIcon
  export const Filter: LucideIcon
  export const FolderOpen: LucideIcon
  export const Globe: LucideIcon
  export const ImageOff: LucideIcon
  export const Inbox: LucideIcon
  export const IndianRupee: LucideIcon
  export const Info: LucideIcon
  export const Languages: LucideIcon
  export const LayoutDashboard: LucideIcon
  export const LineChart: LucideIcon
  export const ListChecks: LucideIcon
  export const Lock: LucideIcon
  export const LogIn: LucideIcon
  export const LogOut: LucideIcon
  export const MailCheck: LucideIcon
  export const MapPin: LucideIcon
  export const Menu: LucideIcon
  export const MessageSquareWarning: LucideIcon
  export const Minus: LucideIcon
  export const Network: LucideIcon
  export const Pencil: LucideIcon
  export const Pin: LucideIcon
  export const Plus: LucideIcon
  export const RefreshCw: LucideIcon
  export const Search: LucideIcon
  export const Settings2: LucideIcon
  export const ShieldAlert: LucideIcon
  export const ShieldCheck: LucideIcon
  export const Sigma: LucideIcon
  export const StickyNote: LucideIcon
  export const Trash2: LucideIcon
  export const TrendingUp: LucideIcon
  export const TriangleAlert: LucideIcon
  export const Type: LucideIcon
  export const Upload: LucideIcon
  export const User2: LucideIcon
  export const UserCog: LucideIcon
  export const UserMinus: LucideIcon
  export const UserPlus: LucideIcon
  export const WifiOff: LucideIcon
  export const X: LucideIcon
  export const XCircle: LucideIcon
}
